version: '3.7'

services:
  mongo:
    image: mongo:latest
    container_name: 'nest_mongo'
    volumes:
      - ./mongodb_data_container:/data/db
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
